kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pipeline2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
  volumeMode: Filesystem